// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: proto/pb_src/share_cars.proto

package pb_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DetectObjects_ObjectType int32

const (
	DetectObjects_VEHICLE    DetectObjects_ObjectType = 0 //車
	DetectObjects_TRUCK      DetectObjects_ObjectType = 1 //トラック
	DetectObjects_PEDESTRIAN DetectObjects_ObjectType = 2 //歩行者
	DetectObjects_OTHER      DetectObjects_ObjectType = 3 //その他のオブジェクト
)

// Enum value maps for DetectObjects_ObjectType.
var (
	DetectObjects_ObjectType_name = map[int32]string{
		0: "VEHICLE",
		1: "TRUCK",
		2: "PEDESTRIAN",
		3: "OTHER",
	}
	DetectObjects_ObjectType_value = map[string]int32{
		"VEHICLE":    0,
		"TRUCK":      1,
		"PEDESTRIAN": 2,
		"OTHER":      3,
	}
)

func (x DetectObjects_ObjectType) Enum() *DetectObjects_ObjectType {
	p := new(DetectObjects_ObjectType)
	*p = x
	return p
}

func (x DetectObjects_ObjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DetectObjects_ObjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_pb_src_share_cars_proto_enumTypes[0].Descriptor()
}

func (DetectObjects_ObjectType) Type() protoreflect.EnumType {
	return &file_proto_pb_src_share_cars_proto_enumTypes[0]
}

func (x DetectObjects_ObjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DetectObjects_ObjectType.Descriptor instead.
func (DetectObjects_ObjectType) EnumDescriptor() ([]byte, []int) {
	return file_proto_pb_src_share_cars_proto_rawDescGZIP(), []int{1, 0}
}

type Vector2D struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Vector2D) Reset() {
	*x = Vector2D{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pb_src_share_cars_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vector2D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector2D) ProtoMessage() {}

func (x *Vector2D) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pb_src_share_cars_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector2D.ProtoReflect.Descriptor instead.
func (*Vector2D) Descriptor() ([]byte, []int) {
	return file_proto_pb_src_share_cars_proto_rawDescGZIP(), []int{0}
}

func (x *Vector2D) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector2D) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type DetectObjects struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcId  string                  `protobuf:"bytes,1,opt,name=src_id,json=srcId,proto3" json:"src_id,omitempty"` // 送信元ID
	Object []*DetectObjects_Object `protobuf:"bytes,2,rep,name=object,proto3" json:"object,omitempty"`            // 検出されたオブジェクト（複数可）
	Hash   *string                 `protobuf:"bytes,3,opt,name=hash,proto3,oneof" json:"hash,omitempty"`          // ハッシュ値（省略可）
}

func (x *DetectObjects) Reset() {
	*x = DetectObjects{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pb_src_share_cars_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetectObjects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectObjects) ProtoMessage() {}

func (x *DetectObjects) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pb_src_share_cars_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectObjects.ProtoReflect.Descriptor instead.
func (*DetectObjects) Descriptor() ([]byte, []int) {
	return file_proto_pb_src_share_cars_proto_rawDescGZIP(), []int{1}
}

func (x *DetectObjects) GetSrcId() string {
	if x != nil {
		return x.SrcId
	}
	return ""
}

func (x *DetectObjects) GetObject() []*DetectObjects_Object {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *DetectObjects) GetHash() string {
	if x != nil && x.Hash != nil {
		return *x.Hash
	}
	return ""
}

type DetectObjects_Object struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       DetectObjects_ObjectType `protobuf:"varint,1,opt,name=type,proto3,enum=test.DetectObjects_ObjectType" json:"type,omitempty"` // 0 to 3
	Confidence float32                  `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`                       // 0.0 to 1.0
	Position   *Vector2D                `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`                             // in meters
	Length     float32                  `protobuf:"fixed32,4,opt,name=length,proto3" json:"length,omitempty"`                               // in meters
}

func (x *DetectObjects_Object) Reset() {
	*x = DetectObjects_Object{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pb_src_share_cars_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetectObjects_Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectObjects_Object) ProtoMessage() {}

func (x *DetectObjects_Object) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pb_src_share_cars_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectObjects_Object.ProtoReflect.Descriptor instead.
func (*DetectObjects_Object) Descriptor() ([]byte, []int) {
	return file_proto_pb_src_share_cars_proto_rawDescGZIP(), []int{1, 0}
}

func (x *DetectObjects_Object) GetType() DetectObjects_ObjectType {
	if x != nil {
		return x.Type
	}
	return DetectObjects_VEHICLE
}

func (x *DetectObjects_Object) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *DetectObjects_Object) GetPosition() *Vector2D {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *DetectObjects_Object) GetLength() float32 {
	if x != nil {
		return x.Length
	}
	return 0
}

var File_proto_pb_src_share_cars_proto protoreflect.FileDescriptor

var file_proto_pb_src_share_cars_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x5f, 0x73, 0x72, 0x63, 0x2f, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x5f, 0x63, 0x61, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x74, 0x65, 0x73, 0x74, 0x22, 0x26, 0x0a, 0x08, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x32,
	0x44, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12,
	0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x22, 0xe0, 0x02,
	0x0a, 0x0d, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12,
	0x15, 0x0a, 0x06, 0x73, 0x72, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x73, 0x72, 0x63, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65,
	0x74, 0x65, 0x63, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2e, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x17, 0x0a, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68,
	0x88, 0x01, 0x01, 0x1a, 0xa0, 0x01, 0x0a, 0x06, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x32,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x74,
	0x65, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x73, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e,
	0x63, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x56, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x32, 0x44, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06,
	0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x3f, 0x0a, 0x0a, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x56, 0x45, 0x48, 0x49, 0x43, 0x4c, 0x45, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x52, 0x55, 0x43, 0x4b, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a,
	0x50, 0x45, 0x44, 0x45, 0x53, 0x54, 0x52, 0x49, 0x41, 0x4e, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05,
	0x4f, 0x54, 0x48, 0x45, 0x52, 0x10, 0x03, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x68, 0x61, 0x73, 0x68,
	0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70,
	0x6a, 0x2d, 0x72, 0x69, 0x6f, 0x6e, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2d, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_pb_src_share_cars_proto_rawDescOnce sync.Once
	file_proto_pb_src_share_cars_proto_rawDescData = file_proto_pb_src_share_cars_proto_rawDesc
)

func file_proto_pb_src_share_cars_proto_rawDescGZIP() []byte {
	file_proto_pb_src_share_cars_proto_rawDescOnce.Do(func() {
		file_proto_pb_src_share_cars_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_pb_src_share_cars_proto_rawDescData)
	})
	return file_proto_pb_src_share_cars_proto_rawDescData
}

var file_proto_pb_src_share_cars_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_pb_src_share_cars_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_pb_src_share_cars_proto_goTypes = []interface{}{
	(DetectObjects_ObjectType)(0), // 0: test.DetectObjects.ObjectType
	(*Vector2D)(nil),              // 1: test.Vector2D
	(*DetectObjects)(nil),         // 2: test.DetectObjects
	(*DetectObjects_Object)(nil),  // 3: test.DetectObjects.Object
}
var file_proto_pb_src_share_cars_proto_depIdxs = []int32{
	3, // 0: test.DetectObjects.object:type_name -> test.DetectObjects.Object
	0, // 1: test.DetectObjects.Object.type:type_name -> test.DetectObjects.ObjectType
	1, // 2: test.DetectObjects.Object.position:type_name -> test.Vector2D
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_pb_src_share_cars_proto_init() }
func file_proto_pb_src_share_cars_proto_init() {
	if File_proto_pb_src_share_cars_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_pb_src_share_cars_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vector2D); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pb_src_share_cars_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetectObjects); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pb_src_share_cars_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetectObjects_Object); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_pb_src_share_cars_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_pb_src_share_cars_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_pb_src_share_cars_proto_goTypes,
		DependencyIndexes: file_proto_pb_src_share_cars_proto_depIdxs,
		EnumInfos:         file_proto_pb_src_share_cars_proto_enumTypes,
		MessageInfos:      file_proto_pb_src_share_cars_proto_msgTypes,
	}.Build()
	File_proto_pb_src_share_cars_proto = out.File
	file_proto_pb_src_share_cars_proto_rawDesc = nil
	file_proto_pb_src_share_cars_proto_goTypes = nil
	file_proto_pb_src_share_cars_proto_depIdxs = nil
}
